# Generated by Django 4.1.2 on 2022-10-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=100)),
                ('asunto', models.TextField()),
                ('cuerpo', models.TextField()),
            ],
        ),
    ]
